# baseURL = 'https://example.org/'
baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
title = ''

theme = 'hugo-template-qubTemplate'

[module]
  [[module.imports]]
    path = "github.com/amertavt/qubt"